music.play(music.stringPlayable("E B C5 A B G A F ", 130), music.PlaybackMode.UntilDone)
basic.showString(" OLA GALERIA ")
basic.pause(100)
basic.showIcon(IconNames.SmallHeart)
basic.pause(100)
basic.showIcon(IconNames.Heart)
basic.pause(100)
basic.showIcon(IconNames.SmallHeart)
basic.pause(100)
basic.showIcon(IconNames.Heart)
basic.pause(100)
basic.showIcon(IconNames.Happy)
basic.pause(100)
